const AIRPORTS = [
  { code: "ATL", name: "Hartsfield-Jackson", city: "Atlanta", country: "US", lat: 33.64, lng: -84.43 },
  { code: "PEK", name: "Capital International", city: "Beijing", country: "CN", lat: 40.08, lng: 116.58 },
  { code: "DXB", name: "Dubai International", city: "Dubai", country: "AE", lat: 25.25, lng: 55.36 },
  { code: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "US", lat: 33.94, lng: -118.41 },
  { code: "HND", name: "Haneda", city: "Tokyo", country: "JP", lat: 35.55, lng: 139.78 },
  { code: "ORD", name: "O'Hare International", city: "Chicago", country: "US", lat: 41.98, lng: -87.90 },
  { code: "LHR", name: "Heathrow", city: "London", country: "GB", lat: 51.47, lng: -0.46 },
  { code: "PVG", name: "Pudong International", city: "Shanghai", country: "CN", lat: 31.14, lng: 121.81 },
  { code: "CDG", name: "Charles de Gaulle", city: "Paris", country: "FR", lat: 49.01, lng: 2.55 },
  { code: "DFW", name: "Dallas/Fort Worth", city: "Dallas", country: "US", lat: 32.90, lng: -97.04 },
  { code: "AMS", name: "Schiphol", city: "Amsterdam", country: "NL", lat: 52.31, lng: 4.76 },
  { code: "FRA", name: "Frankfurt", city: "Frankfurt", country: "DE", lat: 50.03, lng: 8.57 },
  { code: "IST", name: "Istanbul", city: "Istanbul", country: "TR", lat: 41.28, lng: 28.75 },
  { code: "CAN", name: "Baiyun International", city: "Guangzhou", country: "CN", lat: 23.39, lng: 113.30 },
  { code: "JFK", name: "John F. Kennedy", city: "New York", country: "US", lat: 40.64, lng: -73.78 },
  { code: "SIN", name: "Changi", city: "Singapore", country: "SG", lat: 1.35, lng: 103.99 },
  { code: "DEN", name: "Denver International", city: "Denver", country: "US", lat: 39.86, lng: -104.67 },
  { code: "ICN", name: "Incheon International", city: "Seoul", country: "KR", lat: 37.46, lng: 126.44 },
  { code: "BKK", name: "Suvarnabhumi", city: "Bangkok", country: "TH", lat: 13.69, lng: 100.75 },
  { code: "SFO", name: "San Francisco International", city: "San Francisco", country: "US", lat: 37.62, lng: -122.38 },
  { code: "DEL", name: "Indira Gandhi International", city: "Delhi", country: "IN", lat: 28.56, lng: 77.10 },
  { code: "NRT", name: "Narita International", city: "Tokyo", country: "JP", lat: 35.76, lng: 140.39 },
  { code: "SEA", name: "Seattle-Tacoma", city: "Seattle", country: "US", lat: 47.45, lng: -122.31 },
  { code: "MIA", name: "Miami International", city: "Miami", country: "US", lat: 25.80, lng: -80.29 },
  { code: "EWR", name: "Newark Liberty", city: "Newark", country: "US", lat: 40.69, lng: -74.17 },
  { code: "MUC", name: "Munich", city: "Munich", country: "DE", lat: 48.35, lng: 11.79 },
  { code: "MAD", name: "Adolfo Suárez Madrid-Barajas", city: "Madrid", country: "ES", lat: 40.47, lng: -3.57 },
  { code: "BCN", name: "El Prat", city: "Barcelona", country: "ES", lat: 41.30, lng: 2.08 },
  { code: "LGA", name: "LaGuardia", city: "New York", country: "US", lat: 40.78, lng: -73.87 },
  { code: "PHX", name: "Sky Harbor", city: "Phoenix", country: "US", lat: 33.44, lng: -112.01 },
  { code: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "US", lat: 29.98, lng: -95.34 },
  { code: "SYD", name: "Kingsford Smith", city: "Sydney", country: "AU", lat: -33.95, lng: 151.18 },
  { code: "MEL", name: "Tullamarine", city: "Melbourne", country: "AU", lat: -37.67, lng: 144.84 },
  { code: "YYZ", name: "Pearson International", city: "Toronto", country: "CA", lat: 43.68, lng: -79.63 },
  { code: "YVR", name: "Vancouver International", city: "Vancouver", country: "CA", lat: 49.19, lng: -123.18 },
  { code: "BOS", name: "Logan International", city: "Boston", country: "US", lat: 42.36, lng: -71.01 },
  { code: "MSP", name: "Minneapolis-Saint Paul", city: "Minneapolis", country: "US", lat: 44.88, lng: -93.22 },
  { code: "DTW", name: "Detroit Metro", city: "Detroit", country: "US", lat: 42.21, lng: -83.35 },
  { code: "MCO", name: "Orlando International", city: "Orlando", country: "US", lat: 28.43, lng: -81.31 },
  { code: "CLT", name: "Charlotte Douglas", city: "Charlotte", country: "US", lat: 35.21, lng: -80.94 },
  { code: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "US", lat: 36.08, lng: -115.15 },
  { code: "JNB", name: "O.R. Tambo", city: "Johannesburg", country: "ZA", lat: -26.14, lng: 28.25 },
  { code: "CPT", name: "Cape Town International", city: "Cape Town", country: "ZA", lat: -33.97, lng: 18.60 },
  { code: "GRU", name: "Guarulhos", city: "São Paulo", country: "BR", lat: -23.43, lng: -46.47 },
  { code: "MEX", name: "Benito Juárez", city: "Mexico City", country: "MX", lat: 19.44, lng: -99.07 },
  { code: "CUN", name: "Cancún International", city: "Cancún", country: "MX", lat: 21.04, lng: -86.87 },
  { code: "BOG", name: "El Dorado", city: "Bogotá", country: "CO", lat: 4.70, lng: -74.15 },
  { code: "SCL", name: "Arturo Merino Benítez", city: "Santiago", country: "CL", lat: -33.39, lng: -70.79 },
  { code: "EZE", name: "Ministro Pistarini", city: "Buenos Aires", country: "AR", lat: -34.82, lng: -58.54 },
  { code: "LIM", name: "Jorge Chávez", city: "Lima", country: "PE", lat: -12.02, lng: -77.11 },
  { code: "FCO", name: "Fiumicino", city: "Rome", country: "IT", lat: 41.80, lng: 12.25 },
  { code: "MXP", name: "Malpensa", city: "Milan", country: "IT", lat: 45.63, lng: 8.72 },
  { code: "ZRH", name: "Zürich", city: "Zürich", country: "CH", lat: 47.46, lng: 8.56 },
  { code: "VIE", name: "Vienna International", city: "Vienna", country: "AT", lat: 48.11, lng: 16.57 },
  { code: "CPH", name: "Kastrup", city: "Copenhagen", country: "DK", lat: 55.62, lng: 12.66 },
  { code: "OSL", name: "Gardermoen", city: "Oslo", country: "NO", lat: 60.19, lng: 11.10 },
  { code: "ARN", name: "Arlanda", city: "Stockholm", country: "SE", lat: 59.65, lng: 17.94 },
  { code: "HEL", name: "Vantaa", city: "Helsinki", country: "FI", lat: 60.32, lng: 24.97 },
  { code: "LIS", name: "Humberto Delgado", city: "Lisbon", country: "PT", lat: 38.77, lng: -9.13 },
  { code: "DUB", name: "Dublin", city: "Dublin", country: "IE", lat: 53.43, lng: -6.27 },
  { code: "BRU", name: "Brussels", city: "Brussels", country: "BE", lat: 50.90, lng: 4.48 },
  { code: "WAW", name: "Chopin", city: "Warsaw", country: "PL", lat: 52.17, lng: 20.97 },
  { code: "PRG", name: "Václav Havel", city: "Prague", country: "CZ", lat: 50.10, lng: 14.26 },
  { code: "BUD", name: "Ferenc Liszt", city: "Budapest", country: "HU", lat: 47.44, lng: 19.26 },
  { code: "ATH", name: "Eleftherios Venizelos", city: "Athens", country: "GR", lat: 37.94, lng: 23.94 },
  { code: "DOH", name: "Hamad International", city: "Doha", country: "QA", lat: 25.26, lng: 51.61 },
  { code: "AUH", name: "Zayed International", city: "Abu Dhabi", country: "AE", lat: 24.43, lng: 54.65 },
  { code: "TLV", name: "Ben Gurion", city: "Tel Aviv", country: "IL", lat: 32.01, lng: 34.89 },
  { code: "CAI", name: "Cairo International", city: "Cairo", country: "EG", lat: 30.12, lng: 31.41 },
  { code: "NBO", name: "Jomo Kenyatta", city: "Nairobi", country: "KE", lat: -1.32, lng: 36.93 },
  { code: "ADD", name: "Bole International", city: "Addis Ababa", country: "ET", lat: 8.98, lng: 38.80 },
  { code: "CMN", name: "Mohammed V", city: "Casablanca", country: "MA", lat: 33.37, lng: -7.59 },
  { code: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "MY", lat: 2.74, lng: 101.70 },
  { code: "MNL", name: "Ninoy Aquino", city: "Manila", country: "PH", lat: 14.51, lng: 121.02 },
  { code: "CGK", name: "Soekarno-Hatta", city: "Jakarta", country: "ID", lat: -6.13, lng: 106.66 },
  { code: "HKG", name: "Hong Kong International", city: "Hong Kong", country: "HK", lat: 22.31, lng: 113.91 },
  { code: "TPE", name: "Taoyuan International", city: "Taipei", country: "TW", lat: 25.08, lng: 121.23 },
  { code: "BOM", name: "Chhatrapati Shivaji", city: "Mumbai", country: "IN", lat: 19.09, lng: 72.87 },
  { code: "BLR", name: "Kempegowda International", city: "Bangalore", country: "IN", lat: 13.20, lng: 77.71 },
  { code: "AKL", name: "Auckland", city: "Auckland", country: "NZ", lat: -37.01, lng: 174.79 },
  { code: "BNE", name: "Brisbane", city: "Brisbane", country: "AU", lat: -27.38, lng: 153.12 },
  { code: "PER", name: "Perth", city: "Perth", country: "AU", lat: -31.94, lng: 115.97 },
  { code: "SVO", name: "Sheremetyevo", city: "Moscow", country: "RU", lat: 55.97, lng: 37.41 },
  { code: "LED", name: "Pulkovo", city: "St. Petersburg", country: "RU", lat: 59.80, lng: 30.27 },
  { code: "GIG", name: "Galeão", city: "Rio de Janeiro", country: "BR", lat: -22.81, lng: -43.25 },
  { code: "LGW", name: "Gatwick", city: "London", country: "GB", lat: 51.15, lng: -0.19 },
  { code: "STN", name: "Stansted", city: "London", country: "GB", lat: 51.89, lng: 0.26 },
  { code: "MAN", name: "Manchester", city: "Manchester", country: "GB", lat: 53.36, lng: -2.27 },
  { code: "EDI", name: "Edinburgh", city: "Edinburgh", country: "GB", lat: 55.95, lng: -3.37 },
  { code: "ORY", name: "Orly", city: "Paris", country: "FR", lat: 48.73, lng: 2.38 },
  { code: "NCE", name: "Nice Côte d'Azur", city: "Nice", country: "FR", lat: 43.66, lng: 7.22 },
  { code: "DUS", name: "Düsseldorf", city: "Düsseldorf", country: "DE", lat: 51.29, lng: 6.77 },
  { code: "HAM", name: "Hamburg", city: "Hamburg", country: "DE", lat: 53.63, lng: 9.99 },
  { code: "BER", name: "Berlin Brandenburg", city: "Berlin", country: "DE", lat: 52.37, lng: 13.52 },
  { code: "SAN", name: "San Diego International", city: "San Diego", country: "US", lat: 32.73, lng: -117.19 },
  { code: "TPA", name: "Tampa International", city: "Tampa", country: "US", lat: 27.98, lng: -82.53 },
  { code: "PDX", name: "Portland International", city: "Portland", country: "US", lat: 45.59, lng: -122.60 },
  { code: "SLC", name: "Salt Lake City International", city: "Salt Lake City", country: "US", lat: 40.79, lng: -111.98 },
  { code: "BWI", name: "Baltimore/Washington", city: "Baltimore", country: "US", lat: 39.18, lng: -76.67 },
  { code: "DCA", name: "Reagan National", city: "Washington D.C.", country: "US", lat: 38.85, lng: -77.04 },
  { code: "IAD", name: "Dulles International", city: "Washington D.C.", country: "US", lat: 38.95, lng: -77.46 },
  { code: "FLL", name: "Fort Lauderdale-Hollywood", city: "Fort Lauderdale", country: "US", lat: 26.07, lng: -80.15 },
  { code: "HNL", name: "Daniel K. Inouye", city: "Honolulu", country: "US", lat: 21.32, lng: -157.92 },
  { code: "ANC", name: "Ted Stevens", city: "Anchorage", country: "US", lat: 61.17, lng: -150.00 },
  { code: "PHL", name: "Philadelphia International", city: "Philadelphia", country: "US", lat: 39.87, lng: -75.24 },
  { code: "RDU", name: "Raleigh-Durham", city: "Raleigh", country: "US", lat: 35.88, lng: -78.79 },
  { code: "AUS", name: "Austin-Bergstrom", city: "Austin", country: "US", lat: 30.20, lng: -97.67 },
  { code: "BNA", name: "Nashville International", city: "Nashville", country: "US", lat: 36.12, lng: -86.68 },
  { code: "STL", name: "St. Louis Lambert", city: "St. Louis", country: "US", lat: 38.75, lng: -90.37 },
  { code: "MCI", name: "Kansas City International", city: "Kansas City", country: "US", lat: 39.30, lng: -94.71 },
  { code: "IND", name: "Indianapolis International", city: "Indianapolis", country: "US", lat: 39.72, lng: -86.29 },
  { code: "CMH", name: "John Glenn Columbus", city: "Columbus", country: "US", lat: 39.99, lng: -82.89 },
  { code: "PIT", name: "Pittsburgh International", city: "Pittsburgh", country: "US", lat: 40.49, lng: -80.23 },
  { code: "CLE", name: "Cleveland Hopkins", city: "Cleveland", country: "US", lat: 41.41, lng: -81.85 },
  { code: "MKE", name: "General Mitchell", city: "Milwaukee", country: "US", lat: 42.95, lng: -87.90 },
  { code: "OAK", name: "Oakland International", city: "Oakland", country: "US", lat: 37.72, lng: -122.22 },
  { code: "SJC", name: "San José Mineta", city: "San Jose", country: "US", lat: 37.36, lng: -121.93 },
  { code: "SMF", name: "Sacramento International", city: "Sacramento", country: "US", lat: 38.70, lng: -121.59 },
  { code: "YUL", name: "Trudeau International", city: "Montreal", country: "CA", lat: 45.47, lng: -73.74 },
  { code: "YOW", name: "Macdonald-Cartier", city: "Ottawa", country: "CA", lat: 45.32, lng: -75.67 },
  { code: "YYC", name: "Calgary International", city: "Calgary", country: "CA", lat: 51.13, lng: -114.01 },
  { code: "YEG", name: "Edmonton International", city: "Edmonton", country: "CA", lat: 53.31, lng: -113.58 },
  { code: "AGP", name: "Málaga-Costa del Sol", city: "Málaga", country: "ES", lat: 36.67, lng: -4.50 },
  { code: "PMI", name: "Palma de Mallorca", city: "Palma", country: "ES", lat: 39.55, lng: 2.74 },
  { code: "VCE", name: "Marco Polo", city: "Venice", country: "IT", lat: 45.51, lng: 12.35 },
  { code: "NAP", name: "Capodichino", city: "Naples", country: "IT", lat: 40.88, lng: 14.29 },
  { code: "GVA", name: "Geneva", city: "Geneva", country: "CH", lat: 46.24, lng: 6.11 },
  { code: "HAV", name: "José Martí", city: "Havana", country: "CU", lat: 22.99, lng: -82.41 },
  { code: "SJO", name: "Juan Santamaría", city: "San José", country: "CR", lat: 10.00, lng: -84.21 },
  { code: "PTY", name: "Tocumen International", city: "Panama City", country: "PA", lat: 9.07, lng: -79.38 },
  { code: "GDL", name: "Miguel Hidalgo", city: "Guadalajara", country: "MX", lat: 20.52, lng: -103.31 },
  { code: "KIX", name: "Kansai International", city: "Osaka", country: "JP", lat: 34.43, lng: 135.24 },
  { code: "CTS", name: "New Chitose", city: "Sapporo", country: "JP", lat: 42.77, lng: 141.69 },
  { code: "OKA", name: "Naha", city: "Okinawa", country: "JP", lat: 26.20, lng: 127.65 },
  { code: "CMB", name: "Bandaranaike", city: "Colombo", country: "LK", lat: 7.18, lng: 79.88 },
  { code: "DAD", name: "Da Nang International", city: "Da Nang", country: "VN", lat: 16.04, lng: 108.20 },
  { code: "SGN", name: "Tan Son Nhat", city: "Ho Chi Minh City", country: "VN", lat: 10.82, lng: 106.65 },
  { code: "HAN", name: "Noi Bai", city: "Hanoi", country: "VN", lat: 21.22, lng: 105.81 },
  { code: "REP", name: "Siem Reap International", city: "Siem Reap", country: "KH", lat: 13.41, lng: 103.81 },
  { code: "PNH", name: "Phnom Penh International", city: "Phnom Penh", country: "KH", lat: 11.55, lng: 104.84 },
  { code: "RGN", name: "Yangon International", city: "Yangon", country: "MM", lat: 16.91, lng: 96.13 },
  { code: "DPS", name: "Ngurah Rai", city: "Bali", country: "ID", lat: -8.75, lng: 115.17 },
];

const TRAIN_STATIONS = [
  // US
  { name: "Penn Station", city: "New York", country: "US", lat: 40.75, lng: -73.99 },
  { name: "Grand Central", city: "New York", country: "US", lat: 40.75, lng: -73.98 },
  { name: "Union Station", city: "Washington D.C.", country: "US", lat: 38.90, lng: -77.01 },
  { name: "Union Station", city: "Chicago", country: "US", lat: 41.88, lng: -87.64 },
  { name: "Union Station", city: "Los Angeles", country: "US", lat: 34.06, lng: -118.24 },
  { name: "Union Station", city: "Denver", country: "US", lat: 39.75, lng: -105.00 },
  { name: "30th Street Station", city: "Philadelphia", country: "US", lat: 39.96, lng: -75.18 },
  { name: "South Station", city: "Boston", country: "US", lat: 42.35, lng: -71.06 },
  { name: "Back Bay Station", city: "Boston", country: "US", lat: 42.35, lng: -71.07 },
  { name: "King Street Station", city: "Seattle", country: "US", lat: 47.60, lng: -122.33 },
  { name: "Union Station", city: "Portland", country: "US", lat: 45.53, lng: -122.68 },
  { name: "Emeryville Station", city: "San Francisco Bay Area", country: "US", lat: 37.84, lng: -122.29 },
  { name: "Newark Penn Station", city: "Newark", country: "US", lat: 40.73, lng: -74.16 },
  { name: "Trenton Transit Center", city: "Trenton", country: "US", lat: 40.22, lng: -74.76 },
  { name: "New Haven Union Station", city: "New Haven", country: "US", lat: 41.30, lng: -72.93 },
  { name: "Providence Station", city: "Providence", country: "US", lat: 41.83, lng: -71.41 },
  { name: "BWI Rail Station", city: "Baltimore", country: "US", lat: 39.09, lng: -76.68 },
  { name: "Wilmington Station", city: "Wilmington", country: "US", lat: 39.74, lng: -75.55 },
  // UK
  { name: "King's Cross", city: "London", country: "GB", lat: 51.53, lng: -0.12 },
  { name: "St Pancras International", city: "London", country: "GB", lat: 51.53, lng: -0.13 },
  { name: "Paddington", city: "London", country: "GB", lat: 51.52, lng: -0.18 },
  { name: "Waterloo", city: "London", country: "GB", lat: 51.50, lng: -0.11 },
  { name: "Euston", city: "London", country: "GB", lat: 51.53, lng: -0.13 },
  { name: "Liverpool Street", city: "London", country: "GB", lat: 51.52, lng: -0.08 },
  { name: "Victoria", city: "London", country: "GB", lat: 51.50, lng: -0.14 },
  { name: "Edinburgh Waverley", city: "Edinburgh", country: "GB", lat: 55.95, lng: -3.19 },
  { name: "Glasgow Central", city: "Glasgow", country: "GB", lat: 55.86, lng: -4.26 },
  { name: "Manchester Piccadilly", city: "Manchester", country: "GB", lat: 53.48, lng: -2.23 },
  { name: "Birmingham New Street", city: "Birmingham", country: "GB", lat: 52.48, lng: -1.90 },
  { name: "Leeds", city: "Leeds", country: "GB", lat: 53.80, lng: -1.55 },
  { name: "Bristol Temple Meads", city: "Bristol", country: "GB", lat: 51.45, lng: -2.58 },
  { name: "Cardiff Central", city: "Cardiff", country: "GB", lat: 51.47, lng: -3.17 },
  // France
  { name: "Gare du Nord", city: "Paris", country: "FR", lat: 48.88, lng: 2.36 },
  { name: "Gare de Lyon", city: "Paris", country: "FR", lat: 48.84, lng: 2.37 },
  { name: "Gare Montparnasse", city: "Paris", country: "FR", lat: 48.84, lng: 2.32 },
  { name: "Gare de l'Est", city: "Paris", country: "FR", lat: 48.88, lng: 2.36 },
  { name: "Gare Saint-Lazare", city: "Paris", country: "FR", lat: 48.88, lng: 2.33 },
  { name: "Lyon Part-Dieu", city: "Lyon", country: "FR", lat: 45.76, lng: 4.86 },
  { name: "Marseille Saint-Charles", city: "Marseille", country: "FR", lat: 43.30, lng: 5.38 },
  { name: "Bordeaux Saint-Jean", city: "Bordeaux", country: "FR", lat: 44.83, lng: -0.56 },
  { name: "Nice Ville", city: "Nice", country: "FR", lat: 43.70, lng: 7.26 },
  { name: "Strasbourg", city: "Strasbourg", country: "FR", lat: 48.59, lng: 7.73 },
  { name: "Lille Europe", city: "Lille", country: "FR", lat: 50.64, lng: 3.08 },
  { name: "Toulouse Matabiau", city: "Toulouse", country: "FR", lat: 43.61, lng: 1.45 },
  // Germany
  { name: "Berlin Hauptbahnhof", city: "Berlin", country: "DE", lat: 52.53, lng: 13.37 },
  { name: "München Hauptbahnhof", city: "Munich", country: "DE", lat: 48.14, lng: 11.56 },
  { name: "Frankfurt Hauptbahnhof", city: "Frankfurt", country: "DE", lat: 50.11, lng: 8.66 },
  { name: "Hamburg Hauptbahnhof", city: "Hamburg", country: "DE", lat: 53.55, lng: 10.01 },
  { name: "Köln Hauptbahnhof", city: "Cologne", country: "DE", lat: 50.94, lng: 6.96 },
  { name: "Düsseldorf Hauptbahnhof", city: "Düsseldorf", country: "DE", lat: 51.22, lng: 6.79 },
  { name: "Stuttgart Hauptbahnhof", city: "Stuttgart", country: "DE", lat: 48.78, lng: 9.18 },
  { name: "Hannover Hauptbahnhof", city: "Hannover", country: "DE", lat: 52.38, lng: 9.74 },
  { name: "Nürnberg Hauptbahnhof", city: "Nuremberg", country: "DE", lat: 49.45, lng: 11.08 },
  { name: "Leipzig Hauptbahnhof", city: "Leipzig", country: "DE", lat: 51.35, lng: 12.38 },
  { name: "Dresden Hauptbahnhof", city: "Dresden", country: "DE", lat: 51.04, lng: 13.73 },
  // Netherlands / Belgium
  { name: "Amsterdam Centraal", city: "Amsterdam", country: "NL", lat: 52.38, lng: 4.90 },
  { name: "Rotterdam Centraal", city: "Rotterdam", country: "NL", lat: 51.92, lng: 4.47 },
  { name: "Utrecht Centraal", city: "Utrecht", country: "NL", lat: 52.09, lng: 5.11 },
  { name: "Bruxelles-Midi", city: "Brussels", country: "BE", lat: 50.84, lng: 4.34 },
  { name: "Antwerpen-Centraal", city: "Antwerp", country: "BE", lat: 51.22, lng: 4.42 },
  // Switzerland
  { name: "Zürich HB", city: "Zürich", country: "CH", lat: 47.38, lng: 8.54 },
  { name: "Bern", city: "Bern", country: "CH", lat: 46.95, lng: 7.44 },
  { name: "Basel SBB", city: "Basel", country: "CH", lat: 47.55, lng: 7.59 },
  { name: "Geneva Cornavin", city: "Geneva", country: "CH", lat: 46.21, lng: 6.14 },
  // Italy
  { name: "Roma Termini", city: "Rome", country: "IT", lat: 41.90, lng: 12.50 },
  { name: "Milano Centrale", city: "Milan", country: "IT", lat: 45.49, lng: 9.20 },
  { name: "Firenze Santa Maria Novella", city: "Florence", country: "IT", lat: 43.78, lng: 11.25 },
  { name: "Venezia Santa Lucia", city: "Venice", country: "IT", lat: 45.44, lng: 12.32 },
  { name: "Napoli Centrale", city: "Naples", country: "IT", lat: 40.85, lng: 14.27 },
  { name: "Bologna Centrale", city: "Bologna", country: "IT", lat: 44.51, lng: 11.34 },
  { name: "Torino Porta Nuova", city: "Turin", country: "IT", lat: 45.06, lng: 7.68 },
  // Spain
  { name: "Madrid Atocha", city: "Madrid", country: "ES", lat: 40.41, lng: -3.69 },
  { name: "Barcelona Sants", city: "Barcelona", country: "ES", lat: 41.38, lng: 2.14 },
  { name: "Sevilla Santa Justa", city: "Seville", country: "ES", lat: 37.39, lng: -5.97 },
  { name: "Valencia Joaquín Sorolla", city: "Valencia", country: "ES", lat: 39.47, lng: -0.38 },
  { name: "Málaga María Zambrano", city: "Málaga", country: "ES", lat: 36.71, lng: -4.43 },
  // Scandinavia
  { name: "København H", city: "Copenhagen", country: "DK", lat: 55.67, lng: 12.56 },
  { name: "Stockholm Central", city: "Stockholm", country: "SE", lat: 59.33, lng: 18.06 },
  { name: "Göteborg Central", city: "Gothenburg", country: "SE", lat: 57.71, lng: 12.00 },
  { name: "Oslo S", city: "Oslo", country: "NO", lat: 59.91, lng: 10.75 },
  { name: "Helsinki Central", city: "Helsinki", country: "FI", lat: 60.17, lng: 24.94 },
  // Central / Eastern Europe
  { name: "Wien Hauptbahnhof", city: "Vienna", country: "AT", lat: 48.19, lng: 16.38 },
  { name: "Praha hlavní nádraží", city: "Prague", country: "CZ", lat: 50.08, lng: 14.44 },
  { name: "Budapest Keleti", city: "Budapest", country: "HU", lat: 47.50, lng: 19.08 },
  { name: "Warszawa Centralna", city: "Warsaw", country: "PL", lat: 52.23, lng: 21.00 },
  { name: "Kraków Główny", city: "Kraków", country: "PL", lat: 50.07, lng: 19.95 },
  // Japan
  { name: "Tokyo Station", city: "Tokyo", country: "JP", lat: 35.68, lng: 139.77 },
  { name: "Shin-Osaka", city: "Osaka", country: "JP", lat: 34.73, lng: 135.50 },
  { name: "Kyoto Station", city: "Kyoto", country: "JP", lat: 34.99, lng: 135.76 },
  { name: "Nagoya Station", city: "Nagoya", country: "JP", lat: 35.17, lng: 136.88 },
  { name: "Shin-Yokohama", city: "Yokohama", country: "JP", lat: 35.51, lng: 139.62 },
  { name: "Hiroshima Station", city: "Hiroshima", country: "JP", lat: 34.40, lng: 132.47 },
  { name: "Hakata Station", city: "Fukuoka", country: "JP", lat: 33.59, lng: 130.42 },
  { name: "Sendai Station", city: "Sendai", country: "JP", lat: 38.26, lng: 140.88 },
  { name: "Sapporo Station", city: "Sapporo", country: "JP", lat: 43.07, lng: 141.35 },
  // Canada
  { name: "Union Station", city: "Toronto", country: "CA", lat: 43.65, lng: -79.38 },
  { name: "Gare Centrale", city: "Montreal", country: "CA", lat: 45.50, lng: -73.57 },
  { name: "Pacific Central Station", city: "Vancouver", country: "CA", lat: 49.27, lng: -123.10 },
  { name: "Ottawa Station", city: "Ottawa", country: "CA", lat: 45.42, lng: -75.68 },
  // Australia
  { name: "Central Station", city: "Sydney", country: "AU", lat: -33.88, lng: 151.21 },
  { name: "Southern Cross", city: "Melbourne", country: "AU", lat: -37.82, lng: 144.95 },
  // China
  { name: "Beijing South", city: "Beijing", country: "CN", lat: 39.87, lng: 116.38 },
  { name: "Shanghai Hongqiao", city: "Shanghai", country: "CN", lat: 31.19, lng: 121.32 },
  { name: "Guangzhou South", city: "Guangzhou", country: "CN", lat: 22.99, lng: 113.27 },
  { name: "Shenzhen North", city: "Shenzhen", country: "CN", lat: 22.61, lng: 114.03 },
  { name: "Nanjing South", city: "Nanjing", country: "CN", lat: 31.97, lng: 118.80 },
  { name: "Hangzhou East", city: "Hangzhou", country: "CN", lat: 30.29, lng: 120.21 },
  { name: "Chengdu East", city: "Chengdu", country: "CN", lat: 30.63, lng: 104.15 },
  { name: "Xi'an North", city: "Xi'an", country: "CN", lat: 34.39, lng: 108.94 },
  // South Korea
  { name: "Seoul Station", city: "Seoul", country: "KR", lat: 37.55, lng: 126.97 },
  { name: "Busan Station", city: "Busan", country: "KR", lat: 35.12, lng: 129.04 },
  // India
  { name: "New Delhi", city: "Delhi", country: "IN", lat: 28.64, lng: 77.22 },
  { name: "Mumbai Central", city: "Mumbai", country: "IN", lat: 18.97, lng: 72.82 },
  { name: "Howrah Junction", city: "Kolkata", country: "IN", lat: 22.58, lng: 88.34 },
  { name: "Chennai Central", city: "Chennai", country: "IN", lat: 13.08, lng: 80.28 },
  { name: "Bangalore City", city: "Bangalore", country: "IN", lat: 12.98, lng: 77.57 },
  // Portugal
  { name: "Lisboa Santa Apolónia", city: "Lisbon", country: "PT", lat: 38.71, lng: -9.12 },
  { name: "Porto São Bento", city: "Porto", country: "PT", lat: 41.15, lng: -8.61 },
  // Ireland
  { name: "Heuston Station", city: "Dublin", country: "IE", lat: 53.35, lng: -6.29 },
  { name: "Connolly Station", city: "Dublin", country: "IE", lat: 53.35, lng: -6.25 },
];
